
name: Classificatory CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:          
    - name: Docker Compose Action 
      uses: isbang/compose-action@v1.5.1
    - name : Test
      run: ls -l .
    - name : Docker Compose Up
      working-directory: make
      run: docker-compose up
